---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: '4.x'
  install:
    createNamespace: true
  interval: 24h
  targetNamespace: ingress-nginx
  values:
    controller:
      hostPort:
        enabled: true
      ingressClassResource:
        default: true
      kind: DaemonSet
      metrics:
        eabled: true
      service:
        enabled: false

